[build]
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirects para OAuth callback (debe ir ANTES del SPA fallback)
[[redirects]]
  from = "/auth/callback*"
  to = "/auth/callback.html"
  status = 200
  force = true

# SPA fallback para otras rutas (debe ir AL FINAL)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
