[build]
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirects para OAuth callback usando función de Netlify
[[redirects]]
  from = "/auth/callback*"
  to = "/.netlify/functions/auth-callback"
  status = 200
  force = true

# SPA fallback para otras rutas (debe ir AL FINAL)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
